---
abstract: 'Wrapping mod_perl2 applications in Plack'
author:
  - 'Peter Makholm, L<peter@makholm.net>'
  - 'Override subrequest, more cgi.pm support and exit support by Kieren Diment L<zarquon@cpan.org>.'
build_requires: {}
dynamic_config: 0
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-FakeApache
provides:
  Plack::App::FakeApache:
    file: lib/Plack/App/FakeApache.pm
    version: 0.08
  Plack::App::FakeApache::Connection:
    file: lib/Plack/App/FakeApache/Connection.pm
  Plack::App::FakeApache::Log:
    file: lib/Plack/App/FakeApache/Log.pm
  Plack::App::FakeApache::Request:
    file: lib/Plack/App/FakeApache/Request.pm
  Plack::App::FakeApache::Server:
    file: lib/Plack/App/FakeApache/Server.pm
  Plack::App::FakeApache::Tie:
    file: lib/Plack/App/FakeApache.pm
  Plack::App::WrapApacheReq:
    file: lib/Plack/App/WrapApacheReq.pm
requires:
  APR::Pool: 0
  APR::Table: 0
  CGI::Emulate::PSGI: 0
  Plack: 0
  Try::Tiny: 0
resources:
  repository: http://github.com/singingfish/plack-app-wrapapachereq/tree/master
version: 0.08
